### ISSUE TITLE
Marker images missing

### ISSUE THREAD

**Issue by Jabiulla24** [bluehalo/ngx-leaflet#175]
Hello,

I am using `ngx-admin`  (https://github.com/akveo/ngx-admin) and using ngx-leaflet map 

The map is getting rendered but the markers image is not displaying the image is encoded in base 64 it has extra characters which it is not able to render

The asymmetrik/angular2-leaflet version is 2.2.1

    options = {
    layers: [
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' }),
      L.marker([ 12.972442, 77.580643 ]),  // Markers image not displaying 
      ],
    zoom: 5,
    center: L.latLng({ lat: 12.9754246, lng: 77.5926457 }),
  };

Screenshot attached for reference
![imagemissing](https://user-images.githubusercontent.com/24510225/43045766-5b58d2fc-8ddc-11e8-93b6-1b98fc7a12cb.png)

**Comment by nagro** [comment]
Hi, did you try this https://github.com/Asymmetrik/ngx-leaflet#a-note-about-markers ?

**Comment by Jabiulla24** [comment]
Hi,

I used the above code for icon but getting the error in console

       L.icon({
     iconSize: [ 25, 41 ],
     iconAnchor: [ 13, 0 ],
     iconUrl: 'marker-icon.png',
     shadowUrl: 'marker-shadow.png'
      }),


Screenshot of error
![imagemissing2](https://user-images.githubusercontent.com/24510225/43046743-23348894-8deb-11e8-8e3b-6cbde92acd1f.png)

**Comment by reblace** [comment]
The tutorial provides examples of how to use markers with Angular.io:
https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli

In the app.component.ts:

```
paradise = marker([ 46.78465227596462,-121.74141269177198 ], {
    icon: icon({
      iconSize: [ 25, 41 ],
      iconAnchor: [ 13, 41 ],
      iconUrl: 'leaflet/marker-icon.png',
      shadowUrl: 'leaflet/marker-shadow.png'
    })
  });
```

And, you need to include the images in the assets list so Webpack will process them:

```
"assets": [
    {
        "glob": "**/*",
        "input": "./node_modules/leaflet/dist/images",
        "output": "leaflet/"
    },
    "src/favicon.ico",
    "src/assets"
],
```

If you're still having trouble, please provide more code from your component (or a standalone repo so we can reproduce).

**Comment by reblace** [comment]
Did you get anywhere with this?

**Comment by El-Tee-E** [comment]
Had the same problem (btw restart CLI after changing the angular-cli.json) and  solved with instructions in https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli

**Comment by zuzhal** [comment]
Hi, I am still having this problem even after I have tried the solution you have provided. :( 
(sorry I can't push to git now, so i pasted the component here)

`import { Component } from '@angular/core';
import { tileLayer, latLng, marker, icon, polyline } from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-leaflet';

  // Define our base layers so we can reference them multiple times
  streetMaps = tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    detectRetina: true,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  });
  wMaps = tileLayer('http://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png', {
    detectRetina: true,
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
  });

  // Marker for the top of Mt. Ranier
  summit = marker([ 46.8523, -121.7603 ], {
    icon: icon({
      iconSize: [ 25, 41 ],
      iconAnchor: [ 13, 41 ],
      iconUrl: 'assets/marker-icon.png',
      shadowUrl: 'assets/marker-shadow.png'
    })
  });

  // Marker for the parking lot at the base of Mt. Ranier trails
  paradise = marker([ 46.78465227596462,-121.74141269177198 ], {
    icon: icon({
      iconSize: [ 25, 41 ],
      iconAnchor: [ 13, 41 ],
      iconUrl: 'leaflet/marker-icon.png',
      shadowUrl: 'leaflet/marker-shadow.png'
    })
  });

  // Path from paradise to summit - most points omitted from this example for brevity
  route = polyline([[ 46.78465227596462,-121.74141269177198 ],
    [ 46.80047278292477, -121.73470708541572 ],
    [ 46.815471360459924, -121.72521826811135 ],
    [ 46.8360239546746, -121.7323131300509 ],
    [ 46.844306448474526, -121.73327445052564 ],
    [ 46.84979408048093, -121.74325201660395 ],
    [ 46.853193528950214, -121.74823296256363 ],
    [ 46.85322881676257, -121.74843915738165 ],
    [ 46.85119913890958, -121.7519719619304 ],
    [ 46.85103829018772, -121.7542376741767 ],
    [ 46.85101557523012, -121.75431755371392 ],
    [ 46.85140013694763, -121.75727385096252 ],
    [ 46.8525277543813, -121.75995212048292 ],
    [ 46.85290292836726, -121.76049157977104 ],
    [ 46.8528160918504, -121.76042997278273 ]]);

  // Layers control object with our two base layers and the three overlay layers
  layersControl = {
    baseLayers: {
      'Street Maps': this.streetMaps,
      'Wikimedia Maps': this.wMaps
    },
    overlays: {
      'Mt. Rainier Summit': this.summit,
      'Mt. Rainier Paradise Start': this.paradise,
      'Mt. Rainier Climb Route': this.route
    }
  };


  // Set the initial set of displayed layers (we could also use the leafletLayers input binding for this)
  options = {
    layers: [ this.streetMaps, this.route, this.summit, this.paradise ],
    zoom: 7,
    center: latLng([ 46.879966, -121.726909 ])
  };
}
`

**Comment by reblace** [comment]
Closing this as I believe we've provided pointers to the solution for OP.

**Comment by cofad** [comment]
I had this same issue and it was resolved by using the solution provided by @reblace. Just make sure you update the angular.json in the right place. I updated the "test" section accidentally and could not figure out why it wasn't working. I moved it to the "build" section and it worked right away.

For some reason, it  moved the position of the tooltips relative to the markers. I ended up adjusting them to compensate.

    newMarker.bindTooltip(marker.name, {
      direction: "top",
      offset: L.point(0, -30)
    });

**Comment by rbrijesh** [comment]
Set your custom marker icon for ionic 4 leaflet. If its not working. Add icon in your assets folder.
See below code.....

`import { Map, latLng, tileLayer, Layer, marker, icon } from 'leaflet';`

` ionViewDidEnter() {
    this.leafletMap();
  }`

leafletMap() {
    // In setView add latLng and zoom
    this.map = new Map('mapId').setView([28.644800, 77.216721], 10);
    tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {
      attribution: 'edupala.com © ionic LeafLet',
    }).addTo(this.map);

    let greenIcon = icon({
      iconUrl: '../../../assets/icon/favicon.png',
      shadowUrl: '../../../assets/icon/favicon.png',
  
      iconSize:     [38, 95], // size of the icon
      shadowSize:   [50, 64], // size of the shadow
      iconAnchor:   [22, 94], // point of the icon which will correspond to marker's location
      shadowAnchor: [4, 62],  // the same for the shadow
      popupAnchor:  [-3, -76] // point from which the popup should open relative to the iconAnchor
  });

    marker([28.6, 77], { icon: greenIcon }).addTo(this.map)
      .bindPopup('Ionic 4 <br> Leaflet.')
      .openPopup();
  }

If you have shadow image then put it otherwise remove that.

**Comment by fabbioamaral** [comment]
Also, it's worth mentioning that you need to restart your project after modifying your angular.json so the new settings can take place
